### PR TITLE
new-cap to warning instead of error

### PR DESCRIPTION
**Pull request by bramschulting**
If there are errors, the build will fail. We use uppercase function names for some React mixins.

screen shot 2015-07-14 at 11 18 09

### CODE REVIEW

**Comment by jessedijkstra** [comment]
Not too sure about this

**Comment by jtangelder** [comment]
I actually like this setting, naming an not-constructor with a capital goes against the guidelines.

**Comment by jessedijkstra** [comment]
What he says

**Comment by Klaasvaak** [comment]
Agree with Jorik and Jesse. Can we close this?

**Comment by bramschulting** [comment]
I'm fine with an error, but that means we get a linting error everytime we use a mixin.

**Comment by Klaasvaak** [comment]
Just don't use uppercase and it's fixed

**Pull request closed without merging**
