### PR TITLE
Warn about @TODO comments in the code

### PR DESCRIPTION
**Pull request by jessedijkstra**

### CODE REVIEW

**Comment by jtangelder** [comment]
:+1: maybe also for @FIXME (although i've never used that one)

**Comment by jessedijkstra** [comment]
@jtangelder yeah, was thinking bout that, but never used that one either.

Could also set it to anywhere for the keyword todo, so it catches all the todo's, but would rather not.

**Comment by bramschulting** [comment]
Could you add `"@FIXME"` to the terms? I use that during development, if I 'fake' some code. That way I can uninstall a Sublime plugin ;)

image 2015-07-17 at 11 43 13 am

**Comment by jtangelder** [comment]
I did a quick find in the frontend repo, and see that we use both. I can open a PR for this and write them with an @ prefix.

**Comment by jessedijkstra** [comment]
Either with or without @, but not both imho

**Comment by jtangelder** [comment]
I would say lets use the @ prefix, then we can also set `location: 'anywhere'`

**Comment by jessedijkstra** [comment]
yeah

**Comment by jessedijkstra** [comment]
I'll add it

**Comment by jessedijkstra** [comment]
Done

**Comment by jtangelder** [comment]
and location anywhere?

**Comment by jessedijkstra** [comment]
@jtangelder sure

**Comment by jessedijkstra** [comment]
done

**Pull request merged**
